### ISSUE TITLE
[1.0]: Core Mod Update

### ISSUE THREAD

**Issue by KrLite** [DM-Earth/Cabricality#158]
- [X] Code migration
- [ ] New missing mod screen
- [ ] New welcome screen
- [ ] New loading screens

**Comment by KrLite** [comment]
### Milestone Achieved: *<The Horrible Migration to 1.20.1>*

We have migrated the basis to 1.20.1 in a *miserable* manner!
